# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/micr0softstore/android_kernel_samsung_exynos7870-dev-4.x
          kernel-branch: main
          config: exynos7870-j5y17lte_defconfig
          arch: arm64
          aosp-gcc: true
          other-gcc64-url: https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/runtime-gcc-linaro-7.5.0-2019.12-aarch64-linux-gnu.tar.xz
          ksu: true
          ksu-version: main
          android-version: 10
          anykernel3: true
